#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

PYTHON_EXE="${PYTHON_EXE:-$ROOT_DIR/.venv/Scripts/python.exe}"
NODE_EXE="${NODE_EXE:-/c/Program Files/nodejs/node.exe}"

CONFIG_PATH="${CONFIG_PATH:-config.example.json}"
CSV_PATH="${CSV_PATH:-data/demo_krw_btc_15m.csv}"
PAPER_STATE_PATH="${PAPER_STATE_PATH:-data/paper-state.json}"
SELECTOR_STATE_PATH="${SELECTOR_STATE_PATH:-data/selector-state.json}"
LIVE_STATE_PATH="${LIVE_STATE_PATH:-data/live-state.json}"
RELEASE_PACK_DIRECTORY="${RELEASE_PACK_DIRECTORY:-dist/upbit-control-room-release-pack}"
RELEASE_PACK_ZIP_PATH="${RELEASE_PACK_ZIP_PATH:-dist/upbit-control-room-release-pack.zip}"

PAPER_PROFILE_NAME="${PAPER_PROFILE_NAME:-autofinish-paper-main}"
LIVE_PROFILE_NAME="${LIVE_PROFILE_NAME:-autofinish-live-main}"

PAPER_MAX_RESTARTS="${PAPER_MAX_RESTARTS:-2}"
LIVE_MAX_RESTARTS="${LIVE_MAX_RESTARTS:-1}"
RESTART_BACKOFF_SECONDS="${RESTART_BACKOFF_SECONDS:-2}"
REPORT_KEEP_LATEST="${REPORT_KEEP_LATEST:-20}"

ALLOW_LIVE_START="${UPBIT_AUTO_TRADER_ALLOW_LIVE:-0}"

log() {
  printf '[finish] %s\n' "$*"
}

die() {
  printf '[finish] error: %s\n' "$*" >&2
  exit 1
}

require_python() {
  [[ -x "$PYTHON_EXE" ]] || die "python executable not found: $PYTHON_EXE"
}

require_config() {
  [[ -f "$CONFIG_PATH" ]] || die "config not found: $CONFIG_PATH"
}

run_py() {
  "$PYTHON_EXE" -m upbit_auto_trader.main "$@"
}

run_compileall() {
  log "compileall"
  "$PYTHON_EXE" - <<'PY'
import compileall
import sys
ok = compileall.compile_dir("src", quiet=1) and compileall.compile_dir("tests", quiet=1)
print("OK" if ok else "FAIL")
sys.exit(0 if ok else 1)
PY
}

run_node_check() {
  if [[ -x "$NODE_EXE" ]]; then
    log "node --check"
    "$NODE_EXE" --check src/upbit_auto_trader/webui/app.js
  else
    log "skip node --check (node not found at $NODE_EXE)"
  fi
}

run_unittests() {
  log "unittest"
  "$PYTHON_EXE" -m unittest discover -s tests
}

ensure_paper_profile() {
  log "ensure paper profile: $PAPER_PROFILE_NAME"
  run_py profile-save \
    --config "$CONFIG_PATH" \
    --name "$PAPER_PROFILE_NAME" \
    --job-type paper-loop \
    --csv "$CSV_PATH" \
    --state "$PAPER_STATE_PATH" \
    --auto-restart \
    --max-restarts "$PAPER_MAX_RESTARTS" \
    --restart-backoff-seconds "$RESTART_BACKOFF_SECONDS" \
    --report-keep-latest "$REPORT_KEEP_LATEST" \
    --notes "auto-generated by complete_remaining.sh"
}

ensure_live_profile() {
  log "ensure live profile: $LIVE_PROFILE_NAME"
  run_py profile-save \
    --config "$CONFIG_PATH" \
    --name "$LIVE_PROFILE_NAME" \
    --job-type live-daemon \
    --csv "$CSV_PATH" \
    --state "$LIVE_STATE_PATH" \
    --auto-restart \
    --max-restarts "$LIVE_MAX_RESTARTS" \
    --restart-backoff-seconds "$RESTART_BACKOFF_SECONDS" \
    --report-keep-latest "$REPORT_KEEP_LATEST" \
    --notes "auto-generated by complete_remaining.sh"
}

stage_roadmap() {
  cat <<EOF
[finish] Remaining completion roadmap
1. verify
   - compileall, web UI JS syntax check, full unittest
   - command: ./complete_remaining.sh verify
2. paper-preflight
   - doctor, paper profile save, paper profile preview
   - command: ./complete_remaining.sh paper-preflight
3. paper-start
   - start the long-running paper profile in the background
   - command: ./complete_remaining.sh paper-start
4. paper-report
   - export a fresh paper session report
   - command: ./complete_remaining.sh paper-report
5. live-preflight
   - doctor against live state, save live profile, preview live launch blockers
   - command: ./complete_remaining.sh live-preflight
6. live-start
   - starts live daemon only when UPBIT_AUTO_TRADER_ALLOW_LIVE=1
   - command: UPBIT_AUTO_TRADER_ALLOW_LIVE=1 ./complete_remaining.sh live-start
7. release-pack
   - build a distributable release pack zip with support bundle included
   - command: ./complete_remaining.sh release-pack
8. release-verify
   - verify the generated release pack manifest, zip, and support bundle checksums
   - command: ./complete_remaining.sh release-verify
9. release-clean
   - remove generated release pack artifacts
   - command: ./complete_remaining.sh release-clean

Notes
- stages 1, 2, 4, 5 are fully automatable now
- stages 3 and 6 start long-running workers, but real market time still has to pass
- stages 7 and 8 close the release artifact flow under dist/
- live trading still requires valid Upbit keys, readable live state, and upbit.live_enabled=true
EOF
}

stage_verify() {
  require_python
  require_config
  run_compileall
  run_node_check
  run_unittests
}

stage_paper_preflight() {
  require_python
  require_config
  log "paper doctor"
  run_py doctor --config "$CONFIG_PATH" --state "$PAPER_STATE_PATH" --selector-state "$SELECTOR_STATE_PATH"
  ensure_paper_profile
  log "paper profile preview"
  run_py profile-preview --config "$CONFIG_PATH" --profile "$PAPER_PROFILE_NAME"
}

stage_paper_start() {
  require_python
  require_config
  ensure_paper_profile
  log "paper profile start"
  run_py profile-start --config "$CONFIG_PATH" --profile "$PAPER_PROFILE_NAME"
}

stage_paper_report() {
  require_python
  require_config
  log "paper session report"
  run_py session-report \
    --config "$CONFIG_PATH" \
    --state "$PAPER_STATE_PATH" \
    --label "$PAPER_PROFILE_NAME" \
    --keep-latest "$REPORT_KEEP_LATEST"
}

stage_live_preflight() {
  require_python
  require_config
  log "live doctor"
  run_py doctor --config "$CONFIG_PATH" --state "$LIVE_STATE_PATH" --selector-state "$SELECTOR_STATE_PATH"
  ensure_live_profile
  log "live profile preview"
  run_py profile-preview --config "$CONFIG_PATH" --profile "$LIVE_PROFILE_NAME"
}

stage_live_start() {
  require_python
  require_config
  [[ "$ALLOW_LIVE_START" == "1" ]] || die "live start blocked. set UPBIT_AUTO_TRADER_ALLOW_LIVE=1 to proceed"
  ensure_live_profile
  log "live profile start"
  run_py profile-start --config "$CONFIG_PATH" --profile "$LIVE_PROFILE_NAME"
}

stage_release_pack() {
  require_config
  log "build release pack"
  cmd.exe /c build_control_room_release_pack.cmd \
    -OutputDirectory "$RELEASE_PACK_DIRECTORY" \
    -ZipPath "$RELEASE_PACK_ZIP_PATH" \
    -ConfigPath "$CONFIG_PATH" \
    -StatePath "$PAPER_STATE_PATH" \
    -SelectorStatePath "$SELECTOR_STATE_PATH" \
    -IncludeSupportBundle \
    -CreateZip
}

stage_release_verify() {
  log "verify release pack"
  cmd.exe /c verify_control_room_release_pack.cmd \
    -PackDirectory "$RELEASE_PACK_DIRECTORY" \
    -ZipPath "$RELEASE_PACK_ZIP_PATH" \
    -RequireZip \
    -RequireSupportBundle
}

stage_release_clean() {
  log "clean release pack"
  cmd.exe /c clean_control_room_release_pack.cmd \
    -PackDirectory "$RELEASE_PACK_DIRECTORY" \
    -ZipPath "$RELEASE_PACK_ZIP_PATH"
}

stage_status() {
  require_python
  require_config
  log "profiles"
  run_py profile-list --config "$CONFIG_PATH"
  log "reports"
  run_py report-list --config "$CONFIG_PATH"
  log "job history"
  run_py job-history --config "$CONFIG_PATH" --limit 10
}

stage_all_safe() {
  stage_roadmap
  stage_verify
  stage_paper_preflight
  stage_paper_start
  stage_paper_report
  stage_status
  stage_release_pack
  stage_release_verify
}

stage_all() {
  stage_all_safe
  stage_live_preflight
  if [[ "$ALLOW_LIVE_START" == "1" ]]; then
    stage_live_start
  else
    log "skip live-start (set UPBIT_AUTO_TRADER_ALLOW_LIVE=1 to enable)"
  fi
}

stage_help() {
  cat <<EOF
Usage: ./complete_remaining.sh <stage>

Stages
  roadmap
  verify
  paper-preflight
  paper-start
  paper-report
  live-preflight
  live-start
  release-pack
  release-verify
  release-clean
  status
  all-safe
  all
  help

Windows example
  "C:/Program Files/Git/bin/bash.exe" ./complete_remaining.sh all-safe
EOF
}

main() {
  local stage="${1:-help}"
  case "$stage" in
    roadmap) stage_roadmap ;;
    verify) stage_verify ;;
    paper-preflight) stage_paper_preflight ;;
    paper-start) stage_paper_start ;;
    paper-report) stage_paper_report ;;
    live-preflight) stage_live_preflight ;;
    live-start) stage_live_start ;;
    release-pack) stage_release_pack ;;
    release-verify) stage_release_verify ;;
    release-clean) stage_release_clean ;;
    status) stage_status ;;
    all-safe) stage_all_safe ;;
    all) stage_all ;;
    help|-h|--help) stage_help ;;
    *) die "unknown stage: $stage" ;;
  esac
}

main "$@"
