[CmdletBinding()]
param(
    [string]$Stage = "help"
)

$ErrorActionPreference = "Stop"

$RootDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $RootDir

$PythonExe = if ($env:PYTHON_EXE) { $env:PYTHON_EXE } else { Join-Path $RootDir ".venv\Scripts\python.exe" }
$DefaultNodeExe = "C:\Program Files\nodejs\node.exe"
$NodeExe = if ($env:NODE_EXE) { $env:NODE_EXE } else { $DefaultNodeExe }

$ConfigPath = if ($env:CONFIG_PATH) { $env:CONFIG_PATH } else { "config.example.json" }
$CsvPath = if ($env:CSV_PATH) { $env:CSV_PATH } else { "data/demo_krw_btc_15m.csv" }
$PaperStatePath = if ($env:PAPER_STATE_PATH) { $env:PAPER_STATE_PATH } else { "data/paper-state.json" }
$SelectorStatePath = if ($env:SELECTOR_STATE_PATH) { $env:SELECTOR_STATE_PATH } else { "data/selector-state.json" }
$LiveStatePath = if ($env:LIVE_STATE_PATH) { $env:LIVE_STATE_PATH } else { "data/live-state.json" }
$ReleasePackDirectory = if ($env:RELEASE_PACK_DIRECTORY) { $env:RELEASE_PACK_DIRECTORY } else { "dist/upbit-control-room-release-pack" }
$ReleasePackZipPath = if ($env:RELEASE_PACK_ZIP_PATH) { $env:RELEASE_PACK_ZIP_PATH } else { "dist/upbit-control-room-release-pack.zip" }

$PaperProfileName = if ($env:PAPER_PROFILE_NAME) { $env:PAPER_PROFILE_NAME } else { "autofinish-paper-main" }
$LiveProfileName = if ($env:LIVE_PROFILE_NAME) { $env:LIVE_PROFILE_NAME } else { "autofinish-live-main" }

$PaperMaxRestarts = if ($env:PAPER_MAX_RESTARTS) { $env:PAPER_MAX_RESTARTS } else { "2" }
$LiveMaxRestarts = if ($env:LIVE_MAX_RESTARTS) { $env:LIVE_MAX_RESTARTS } else { "1" }
$RestartBackoffSeconds = if ($env:RESTART_BACKOFF_SECONDS) { $env:RESTART_BACKOFF_SECONDS } else { "2" }
$ReportKeepLatest = if ($env:REPORT_KEEP_LATEST) { $env:REPORT_KEEP_LATEST } else { "20" }
$AllowLiveStart = if ($env:UPBIT_AUTO_TRADER_ALLOW_LIVE) { $env:UPBIT_AUTO_TRADER_ALLOW_LIVE } else { "0" }

function Write-FinishLog {
    param([string]$Message)
    Write-Host ("[finish] {0}" -f $Message)
}

function Fail-Step {
    param([string]$Message)
    throw ("[finish] error: {0}" -f $Message)
}

function Require-Python {
    if (-not (Test-Path $PythonExe)) {
        Fail-Step "python executable not found: $PythonExe"
    }
}

function Require-Config {
    if (-not (Test-Path $ConfigPath)) {
        Fail-Step "config not found: $ConfigPath"
    }
}

function Invoke-PythonMain {
    param([string[]]$Arguments)
    & $PythonExe -m upbit_auto_trader.main @Arguments
    if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
    }
}

function Invoke-CompileAll {
    Write-FinishLog "compileall"
    @'
import compileall
import sys
ok = compileall.compile_dir("src", quiet=1) and compileall.compile_dir("tests", quiet=1)
print("OK" if ok else "FAIL")
sys.exit(0 if ok else 1)
'@ | & $PythonExe -
    if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
    }
}

function Invoke-NodeCheck {
    if (Test-Path $NodeExe) {
        Write-FinishLog "node --check"
        & $NodeExe --check "src\upbit_auto_trader\webui\app.js"
        if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
        }
        return
    }
    Write-FinishLog "skip node --check (node not found at $NodeExe)"
}

function Invoke-UnitTests {
    Write-FinishLog "unittest"
    & $PythonExe -m unittest discover -s tests
    if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
    }
}

function Ensure-PaperProfile {
    Write-FinishLog ("ensure paper profile: {0}" -f $PaperProfileName)
    Invoke-PythonMain @(
        "profile-save",
        "--config", $ConfigPath,
        "--name", $PaperProfileName,
        "--job-type", "paper-loop",
        "--csv", $CsvPath,
        "--state", $PaperStatePath,
        "--auto-restart",
        "--max-restarts", $PaperMaxRestarts,
        "--restart-backoff-seconds", $RestartBackoffSeconds,
        "--report-keep-latest", $ReportKeepLatest,
        "--notes", "auto-generated by complete_remaining.ps1"
    )
}

function Ensure-LiveProfile {
    Write-FinishLog ("ensure live profile: {0}" -f $LiveProfileName)
    Invoke-PythonMain @(
        "profile-save",
        "--config", $ConfigPath,
        "--name", $LiveProfileName,
        "--job-type", "live-daemon",
        "--csv", $CsvPath,
        "--state", $LiveStatePath,
        "--auto-restart",
        "--max-restarts", $LiveMaxRestarts,
        "--restart-backoff-seconds", $RestartBackoffSeconds,
        "--report-keep-latest", $ReportKeepLatest,
        "--notes", "auto-generated by complete_remaining.ps1"
    )
}

function Invoke-StageRoadmap {
    @"
[finish] Remaining completion roadmap
1. verify
   - compileall, web UI JS syntax check, full unittest
   - command: .\complete_remaining.cmd verify
2. paper-preflight
   - doctor, paper profile save, paper profile preview
   - command: .\complete_remaining.cmd paper-preflight
3. paper-start
   - start the long-running paper profile in the background
   - command: .\complete_remaining.cmd paper-start
4. paper-report
   - export a fresh paper session report
   - command: .\complete_remaining.cmd paper-report
5. live-preflight
   - doctor against live state, save live profile, preview live launch blockers
   - command: .\complete_remaining.cmd live-preflight
6. live-start
   - starts live daemon only when UPBIT_AUTO_TRADER_ALLOW_LIVE=1
   - command: set UPBIT_AUTO_TRADER_ALLOW_LIVE=1 && .\complete_remaining.cmd live-start
7. release-pack
   - build a distributable release pack zip with support bundle included
   - command: .\complete_remaining.cmd release-pack
8. release-verify
   - verify the generated release pack manifest, zip, and support bundle checksums
   - command: .\complete_remaining.cmd release-verify
9. release-clean
   - remove generated release pack artifacts
   - command: .\complete_remaining.cmd release-clean

Notes
- stages 1, 2, 4, 5 are fully automatable now
- stages 3 and 6 start long-running workers, but real market time still has to pass
- stages 7 and 8 close the release artifact flow under dist/
- live trading still requires valid Upbit keys, readable live state, and upbit.live_enabled=true
"@
}

function Invoke-StageVerify {
    Require-Python
    Require-Config
    Invoke-CompileAll
    Invoke-NodeCheck
    Invoke-UnitTests
}

function Invoke-StagePaperPreflight {
    Require-Python
    Require-Config
    Write-FinishLog "paper doctor"
    Invoke-PythonMain @("doctor", "--config", $ConfigPath, "--state", $PaperStatePath, "--selector-state", $SelectorStatePath)
    Ensure-PaperProfile
    Write-FinishLog "paper profile preview"
    Invoke-PythonMain @("profile-preview", "--config", $ConfigPath, "--profile", $PaperProfileName)
}

function Invoke-StagePaperStart {
    Require-Python
    Require-Config
    Ensure-PaperProfile
    Write-FinishLog "paper profile start"
    Invoke-PythonMain @("profile-start", "--config", $ConfigPath, "--profile", $PaperProfileName)
}

function Invoke-StagePaperReport {
    Require-Python
    Require-Config
    Write-FinishLog "paper session report"
    Invoke-PythonMain @(
        "session-report",
        "--config", $ConfigPath,
        "--state", $PaperStatePath,
        "--label", $PaperProfileName,
        "--keep-latest", $ReportKeepLatest
    )
}

function Invoke-StageLivePreflight {
    Require-Python
    Require-Config
    Write-FinishLog "live doctor"
    Invoke-PythonMain @("doctor", "--config", $ConfigPath, "--state", $LiveStatePath, "--selector-state", $SelectorStatePath)
    Ensure-LiveProfile
    Write-FinishLog "live profile preview"
    Invoke-PythonMain @("profile-preview", "--config", $ConfigPath, "--profile", $LiveProfileName)
}

function Invoke-StageLiveStart {
    Require-Python
    Require-Config
    if ($AllowLiveStart -ne "1") {
        Fail-Step "live start blocked. set UPBIT_AUTO_TRADER_ALLOW_LIVE=1 to proceed"
    }
    Ensure-LiveProfile
    Write-FinishLog "live profile start"
    Invoke-PythonMain @("profile-start", "--config", $ConfigPath, "--profile", $LiveProfileName)
}

function Invoke-StageReleasePack {
    Require-Config
    $releasePackScript = Join-Path $RootDir "build_control_room_release_pack.cmd"
    if (-not (Test-Path $releasePackScript)) {
        Fail-Step "release pack wrapper not found: $releasePackScript"
    }
    Write-FinishLog "build release pack"
    & $releasePackScript `
        -OutputDirectory $ReleasePackDirectory `
        -ZipPath $ReleasePackZipPath `
        -ConfigPath $ConfigPath `
        -StatePath $PaperStatePath `
        -SelectorStatePath $SelectorStatePath `
        -IncludeSupportBundle `
        -CreateZip
    if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
    }
}

function Invoke-StageReleaseVerify {
    $verifyScript = Join-Path $RootDir "verify_control_room_release_pack.cmd"
    if (-not (Test-Path $verifyScript)) {
        Fail-Step "release pack verify wrapper not found: $verifyScript"
    }
    Write-FinishLog "verify release pack"
    & $verifyScript `
        -PackDirectory $ReleasePackDirectory `
        -ZipPath $ReleasePackZipPath `
        -RequireZip `
        -RequireSupportBundle
    if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
    }
}

function Invoke-StageReleaseClean {
    $cleanScript = Join-Path $RootDir "clean_control_room_release_pack.cmd"
    if (-not (Test-Path $cleanScript)) {
        Fail-Step "release pack cleanup wrapper not found: $cleanScript"
    }
    Write-FinishLog "clean release pack"
    & $cleanScript -PackDirectory $ReleasePackDirectory -ZipPath $ReleasePackZipPath
    if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
    }
}

function Invoke-StageStatus {
    Require-Python
    Require-Config
    Write-FinishLog "release status"
    Invoke-PythonMain @("release-status", "--config", $ConfigPath)
    Write-FinishLog "profiles"
    Invoke-PythonMain @("profile-list", "--config", $ConfigPath)
    Write-FinishLog "reports"
    Invoke-PythonMain @("report-list", "--config", $ConfigPath)
    Write-FinishLog "job history"
    Invoke-PythonMain @("job-history", "--config", $ConfigPath, "--limit", "10")
}

function Invoke-StageAllSafe {
    Invoke-StageRoadmap
    Invoke-StageVerify
    Invoke-StagePaperPreflight
    Invoke-StagePaperStart
    Invoke-StagePaperReport
    Invoke-StageStatus
    Invoke-StageReleasePack
    Invoke-StageReleaseVerify
}

function Invoke-StageAll {
    Invoke-StageAllSafe
    Invoke-StageLivePreflight
    if ($AllowLiveStart -eq "1") {
        Invoke-StageLiveStart
        return
    }
    Write-FinishLog "skip live-start (set UPBIT_AUTO_TRADER_ALLOW_LIVE=1 to enable)"
}

function Invoke-StageHelp {
    @"
Usage: .\complete_remaining.ps1 <stage>

Stages
  roadmap
  verify
  paper-preflight
  paper-start
  paper-report
  live-preflight
  live-start
  release-pack
  release-verify
  release-clean
  status
  all-safe
  all
  help

Windows examples
  .\complete_remaining.cmd all-safe
  powershell -ExecutionPolicy Bypass -File .\complete_remaining.ps1 all-safe
"@
}

switch ($Stage) {
    "roadmap" { Invoke-StageRoadmap }
    "verify" { Invoke-StageVerify }
    "paper-preflight" { Invoke-StagePaperPreflight }
    "paper-start" { Invoke-StagePaperStart }
    "paper-report" { Invoke-StagePaperReport }
    "live-preflight" { Invoke-StageLivePreflight }
    "live-start" { Invoke-StageLiveStart }
    "release-pack" { Invoke-StageReleasePack }
    "release-verify" { Invoke-StageReleaseVerify }
    "release-clean" { Invoke-StageReleaseClean }
    "status" { Invoke-StageStatus }
    "all-safe" { Invoke-StageAllSafe }
    "all" { Invoke-StageAll }
    "help" { Invoke-StageHelp }
    "-h" { Invoke-StageHelp }
    "--help" { Invoke-StageHelp }
    default { Fail-Step ("unknown stage: {0}" -f $Stage) }
}
